name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: setup-nodejs 
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.5

      - name: npm install and npm run build
        run: |
          npm ci
          npm run build:ci
